name: ML Code Tests for yang-mlops-project-0912
'on':
  workflow_dispatch: null
  pull_request:
    paths-ignore:
    - databricks-config/**
env:
  DATABRICKS_HOST: https://adb-8405830731420074.14.azuredatabricks.net
  NODE_TYPE_ID: Standard_D3_v2
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        pip install -r test-requirements.txt

        '
    - name: Run tests with pytest
      run: pytest
  integration_test:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Generate AAD Token
      run: ./.github/workflows/scripts/generate-aad-token.sh ${{ secrets.STAGING_AZURE_SP_TENANT_ID
        }} ${{ secrets.STAGING_AZURE_SP_APPLICATION_ID }} ${{ secrets.STAGING_AZURE_SP_CLIENT_SECRET
        }}
    - name: Train model
      uses: databricks/run-notebook@v0
      id: train
      with:
        local-notebook-path: notebooks/Train.py
        git-commit: ${{ github.event.pull_request.head.sha || github.sha }}
        new-cluster-json: "{\n  \"spark_version\": \"11.0.x-cpu-ml-scala2.12\",\n\
          \  \"num_workers\": 0,\n  \"spark_conf\": {\n    \"spark.databricks.cluster.profile\"\
          : \"singleNode\",\n    \"spark.master\": \"local[*, 4]\"\n  },\n  \"node_type_id\"\
          : \"${{ env.NODE_TYPE_ID }}\",\n  \"custom_tags\": {\n    \"ResourceClass\"\
          : \"SingleNode\"\n  }\n}\n"
        access-control-list-json: "[\n  {\n    \"group_name\": \"users\",\n    \"\
          permission_level\": \"CAN_VIEW\"\n  }\n]\n"
        run-name: yang-mlops-project-0912 Integration Test
        notebook-params-json: "{\n  \"env\": \"staging\",\n  \"test_mode\": \"True\"\
          \n}            \n"
