name: Terraform Tests for yang-mlops-project-0912
'on':
  workflow_dispatch: null
  pull_request_target:
    paths:
    - databricks-config/**
defaults:
  run:
    working-directory: ./databricks-config
jobs:
  staging:
    concurrency: yang-mlops-project-0912-staging-terraform-job
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://adb-8405830731420074.14.azuredatabricks.net
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - name: Generate AAD Token
      run: ../.github/workflows/scripts/generate-aad-token.sh ${{ secrets.STAGING_AZURE_SP_TENANT_ID
        }} ${{ secrets.STAGING_AZURE_SP_APPLICATION_ID }} ${{ secrets.STAGING_AZURE_SP_CLIENT_SECRET
        }}
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -recursive -diff
      continue-on-error: true
    - name: Configure Terraform state backend authentication
      run: '# Below we assume you''ve run the setup scripts under the cicd-setup-scripts
        directory

        # to create an Azure storage container and store its associated Azure ARM
        key as a Github Actions secret with

        # name ARM_ACCESS_KEY. We set the ARM_ACCESS_KEY environment variable to authenticate
        to the azurerm

        # backend as described in https://www.terraform.io/language/settings/backends/azurerm

        echo "ARM_ACCESS_KEY=${{secrets.ARM_ACCESS_KEY}}" >> "$GITHUB_ENV"

        '
    - name: Terraform Init
      id: init
      run: terraform -chdir=staging init
    - name: Terraform Validate
      id: validate
      run: terraform -chdir=staging validate -no-color
    - name: Terraform Plan
      id: plan
      run: 'terraform -chdir=staging plan -no-color \

        -var="git_repo_url=${{ github.server_url }}/${{ github.repository }}"

        '
    - name: Create Comment with Terraform Plan
      uses: actions/github-script@v6
      id: comment
      env:
        PLAN: 'terraform

          ${{ steps.plan.outputs.stdout }}'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "const output = `#### Terraform Staging Format and Style \U0001F58C\
          \ \\`${{ steps.fmt.outcome }}\\`\n#### Terraform Staging Initialization\
          \ \u2699\uFE0F \\`${{ steps.init.outcome }}\\`\n#### Terraform Staging Validation\
          \ \U0001F916 \\`${{ steps.validate.outcome }}\\`\n<details><summary>Staging\
          \ Validation Output</summary>\n\n\\`\\`\\`\\n\n${{ steps.validate.outputs.stdout\
          \ }}\n\\`\\`\\`\n\n</details>\n\n#### Terraform Staging Plan \U0001F4D6\
          \ \\`${{ steps.plan.outcome }}\\`\n\n<details><summary>Show Staging Plan</summary>\n\
          \n\\`\\`\\`\\n\n${process.env.PLAN}\n\\`\\`\\`\n\n</details>`\n\ngithub.rest.issues.createComment({\n\
          \  issue_number: context.issue.number,\n  owner: context.repo.owner,\n \
          \ repo: context.repo.repo,\n  body: output\n})\n"
  prod:
    concurrency: yang-mlops-project-0912-prod-terraform-job
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://adb-1005182519515014.14.azuredatabricks.net
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - name: Generate AAD Token
      run: ../.github/workflows/scripts/generate-aad-token.sh ${{ secrets.PROD_AZURE_SP_TENANT_ID
        }} ${{ secrets.PROD_AZURE_SP_APPLICATION_ID }} ${{ secrets.PROD_AZURE_SP_CLIENT_SECRET
        }}
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -recursive -diff
      continue-on-error: true
    - name: Configure Terraform state backend authentication
      run: 'echo "ARM_ACCESS_KEY=${{secrets.ARM_ACCESS_KEY}}" >> "$GITHUB_ENV"

        '
    - name: Terraform Init
      id: init
      run: terraform -chdir=prod init
    - name: Terraform Validate
      id: validate
      run: terraform -chdir=prod validate -no-color
    - name: Terraform Plan
      id: plan
      run: 'terraform -chdir=prod plan -no-color \

        -var="git_repo_url=${{ github.server_url }}/${{ github.repository }}"

        '
    - name: Create Comment with Terraform Plan
      uses: actions/github-script@v6
      id: comment
      env:
        PLAN: 'terraform

          ${{ steps.plan.outputs.stdout }}'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "const output = `#### Terraform Prod Format and Style \U0001F58C \\\
          `${{ steps.fmt.outcome }}\\`\n#### Terraform Prod Initialization \u2699\uFE0F\
          \ \\`${{ steps.init.outcome }}\\`\n#### Terraform Prod Validation \U0001F916\
          \ \\`${{ steps.validate.outcome }}\\`\n<details><summary>Prod Validation\
          \ Output</summary>\n\n\\`\\`\\`\\n\n${{ steps.validate.outputs.stdout }}\n\
          \\`\\`\\`\n\n</details>\n\n#### Terraform Prod Plan \U0001F4D6 \\`${{ steps.plan.outcome\
          \ }}\\`\n\n<details><summary>Show Prod Plan</summary>\n\n\\`\\`\\`\\n\n\
          ${process.env.PLAN}\n\\`\\`\\`\n\n</details>`\n\ngithub.rest.issues.createComment({\n\
          \  issue_number: context.issue.number,\n  owner: context.repo.owner,\n \
          \ repo: context.repo.repo,\n  body: output\n})\n"
